### ISSUE TITLE
Confusion on algebra of 3.2

### ISSUE THREAD

**Issue by AdamISZ** [kayabaNerve/fcmp-plus-plus-paper#1]
Hi,
Not sure if this is an error, a typo, or I just misunderstood something but, referring to the first part of Section 3.2, we are proving a relation:

$$G, T, U, V \in \mathbb{G}, \tilde{O}, \tilde{I}, R, L \in \mathbb{G};
x, y', r_i, r_j \in \mathbb{Z} | \tilde{O} = x \cdot G + y' \cdot T, R = r_i \cdot V + r_j \cdot T, L = x \tilde{I} - \left(xr_i\right) \cdot U
$$

Then $r_p, \alpha, \beta, \mu, \delta$ are all sampled by prover and we define $P$, $A$ and $B$ from the random samples and the witness as per the doc. And the responses $s_{\alpha}, s_{\beta}, s_{\delta}$ are defined.

I can't get the verification equation to match up. The LHS is $e^2 P + eA + B$. That expands out as:

$$e^2 x G + e^2 r_i V + e^2 x r_i U + e^2 r_p T + e\alpha G + e\beta V + \left(e\alpha y + e\beta x\right)U + e \delta T + \alpha \beta U + \mu T
$$

which can be rearranged to:

$$e(\alpha + ex)G + e(\beta + ex)V + (e^2 x r_i + e(\alpha y + \beta x) + \alpha \beta)U + (\mu + e(er_p + \delta))T$$

The coefficient for $U$ should simplify to $s_{\alpha}s_{\beta}$ for correctness, but that is $(e^2 x r_i + e(\alpha r_i + \beta x) + \alpha \beta)$, i.e. it has $r_i$ in place of $y$.

Not sure but is it perhaps only that the definition of $A = \alpha \cdot G + \beta \cdot V + ((\alpha y) + (\beta x)) \cdot U + \delta \cdot T$ should replace $y$ with $r_i$, here?

**Comment by kayabaNerve** [comment]
Yep! This was found by Aaron Feickert in their review and I was made aware... five days ago? I hadn't gotten around to updating the document with a fix, as I wanted to wait for Feickert to finish their review so I could properly cite it (and it wasn't urgent, I knew the issue and I'm the one implementing this math, and it also doesn't affect other active milestones), but you're absolutely correct.

I'll also note your independent finding in the fix commit :+1:

**Comment by AdamISZ** [comment]
> Yep! This was found by Aaron Feickert in their review and I was made aware... five days ago? I hadn't gotten around to updating the document with a fix, as I wanted to wait for Feickert to finish their review so I could properly cite it (and it wasn't urgent, I knew the issue and I'm the one implementing this math, and it also doesn't affect other active milestones), but you're absolutely correct.
> 
> I'll also note your independent finding in the fix commit 👍

OK good. This morning I actually took the trouble to read the relevant part of Bulletproofs +  (Fig 1, n=1 case); yes that makes it clear it should be $r_i$ in place of $y$ there, in the definition of the commitment $A$.
